name: Publish to npm (OIDC)

on:
  push:
    tags:
      - "v*.*.*" # Publish when a version tag like v0.1.0 is pushed
  workflow_dispatch: {}

# Required for npm Trusted Publishing via GitHub OIDC
permissions:
  contents: read
  id-token: write

jobs:
  publish:
    name: Publish package to npm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

      - name: Run tests
        run: npm test --if-present

      - name: Ensure tag matches package.json version
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          VERSION=${TAG#v}
          PKG_VERSION=$(node -p "require('./package.json').version")
          echo "Tag: $VERSION | package.json: $PKG_VERSION"
          if [ "$VERSION" != "$PKG_VERSION" ]; then
            echo "Error: git tag version does not match package.json version" >&2
            exit 1
          fi

      # prepublishOnly runs `npm run build` automatically
      - name: Publish to npm (Trusted Publishing)
        run: npm publish --provenance --access public
